### ISSUE TITLE
Sorry, but I don't use CMake!

### ISSUE THREAD

**Issue by iahung2** [soasis/cuneicode#8]
Please tell me how to do manual deployment to get started. I have no problems building people's software with CMake, but I personally don't use CMake as the build system for my code. I'm a hobbyist and I prefer using an IDE that I could click and have it build and run my program instead of having to write a build script. I don't want to use CMake, including CMake GUI.

**Comment by ThePhD** [comment]
It seems like you're closing all of your issues, but I guess I'll just leave a response here in case anyone else wanders by:

the reason we chose CMake is because, eventually, there's dependencies and other libraries that need to be pulled in to have this code work. Particularly, we use a bunch of our own home-grown stuff, from ztd.idk, ztd.encoding_tables, and similar.

If you pull the source of all those libraries and set up the include paths, as well as build all the files contained in each `source/` folder, you can just... have the library. I wouldn't recommend it because it'd be a pain in the ass to update, but that's the tradeoff you'd have to make.

I was working on a "single" script that could trawl through dependencies and compose one mega-header for users, but I have not completed that work. My apologies.

**Comment by g-berthiaume** [comment]
> the reason we chose CMake is because, eventually, there's dependencies and other libraries that need to be pulled in to have this code work. Particularly, we use a bunch of our own home-grown stuff, from ztd.idk, ztd.encoding_tables, and similar.

That's a bummer, but I can understand the rational.

Maybe the solution is not to provide more build system, but to provide a simpler project to build.
e.g. you could have a script to combine header and source files together to create a `cuneicode.h` and `cuneicode.c` à la SQLite `sqlite3-all.c`. 

Building the lib becomes trivial, so you don't need to spend time to maintain a `make`, `ninja`, `build.zig`, `meson.py`, `xmake`, etc
